name: Rust

on:
  push:
    branches: ["main"]
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo build --release --target wasm32-unknown-unknown
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/wasm32-unknown-unknown/release/*.wasm"
          token: ${{ secrets.GITHUB_TOKEN }}
